### ISSUE TITLE
v1.0.0 Release

### ISSUE THREAD

**Issue by scaramallion** [pydicom/pylibjpeg#1]
- [x] Add test coverage
  - [x] Add tests for pixel data handler (#4)
  - [x] Add tests for decode and reconstruct (#19, #22)
- [x] Add ability to retrieve JPEG parameter data (#19)
- [x] Add ability to retrieve to numpy array without needing to go through pydicom (#19)
- [x] Add return status code to `Decode()` and exceptions (#13)
- [x] Housekeeping stuff
  - [x] Add Travis builds
  - [x] Fix up setup
  - [x] Check install somehow - travis osx and windows builds
  - [x] Add versioning
- [x] Add documentation
- [x] Add to pypi
  - [x] Configuration for building wheels
- [x] Move to pydicom org
